// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvoO8dN8vSVrDH-2p2E3TNwat0ogTVIiY',
    appId: '1:787936137377:web:cb3b62ae8a035ef53de0e0',
    messagingSenderId: '787936137377',
    projectId: 'sofradeneme',
    authDomain: 'sofradeneme.firebaseapp.com',
    storageBucket: 'sofradeneme.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxh1WY36R_z4fru-LeKaqj6utaBS47W1s',
    appId: '1:787936137377:android:e36daa79727d00c23de0e0',
    messagingSenderId: '787936137377',
    projectId: 'sofradeneme',
    storageBucket: 'sofradeneme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSkIXoafE4ZsOLFwE8HNqa-WrO78dzBxs',
    appId: '1:787936137377:ios:550ad84cd6665f073de0e0',
    messagingSenderId: '787936137377',
    projectId: 'sofradeneme',
    storageBucket: 'sofradeneme.appspot.com',
    iosBundleId: 'com.example.denemelers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSkIXoafE4ZsOLFwE8HNqa-WrO78dzBxs',
    appId: '1:787936137377:ios:550ad84cd6665f073de0e0',
    messagingSenderId: '787936137377',
    projectId: 'sofradeneme',
    storageBucket: 'sofradeneme.appspot.com',
    iosBundleId: 'com.example.denemelers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvoO8dN8vSVrDH-2p2E3TNwat0ogTVIiY',
    appId: '1:787936137377:web:e17e3d4ee4e440b73de0e0',
    messagingSenderId: '787936137377',
    projectId: 'sofradeneme',
    authDomain: 'sofradeneme.firebaseapp.com',
    storageBucket: 'sofradeneme.appspot.com',
  );
}
